import Sidebar from "@/components/Sidebar";
import type { Metadata } from "next";
import localFont from "next/font/local";
import ApolloContainer from "../containers/ApolloContainer";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ApolloContainer>
          <div className="flex">
            <aside className="fixed top-0 w-64 h-screen border-r border-r-gray-500 border-opacity-45">
              <Sidebar />
            </aside>
            <div className="main">
              <main className="container mx-auto">{children}</main>
            </div>
          </div>
        </ApolloContainer>
      </body>
    </html>
  );
}
